# RuboCop configuration for SketchUp Ruby extension

plugins:
  - rubocop-performance
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

# SketchUp specific adjustments
Style/Documentation:
  Enabled: false  # SketchUp extensions often don't need full class documentation

Metrics:
  Enabled: false  # Metrics limits are too restrictive for SketchUp scripts

Layout/LineLength:
  Max: 100  # Reasonable line length for Ruby

Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Naming/MethodParameterName:
  Enabled: false

Style/GlobalVars:
  AllowedVariables:
    - '$SKETCHUP_CONSOLE'  # SketchUp global console

# Allow rescue without explicit error class for SketchUp compatibility
Style/RescueStandardError:
  Enabled: false
