#!/usr/bin/env ruby
# frozen_string_literal: true

require 'yard'
require 'fileutils'

# Build a concise INDEX.md for Claude Code to navigate the API documentation

puts "Loading YARD registry..."
YARD::Registry.load!('.yardoc')

# Group objects by top-level namespace
grouped_objects = Hash.new { |h, k| h[k] = [] }

# Collect all documented objects
[:class, :module, :method, :constant].each do |type|
  YARD::Registry.all(type).each do |obj|
    # Skip undocumented objects
    next if obj.docstring.blank?

    # Extract summary (first sentence)
    summary = obj.docstring.summary.strip
    summary = summary[0..100] + '...' if summary.length > 100

    # Determine top-level namespace
    path_parts = obj.path.split('::')
    namespace = path_parts.first || 'Global'

    grouped_objects[namespace] << {
      path: obj.path,
      type: type.to_s,
      summary: summary,
      version: obj.tag(:version)&.text
    }
  end
end

puts "Found #{grouped_objects.values.flatten.size} documented objects"
puts "Grouped into #{grouped_objects.keys.size} namespaces"

# Sort namespaces alphabetically
sorted_namespaces = grouped_objects.keys.sort

# Build INDEX.md
output_path = 'generated-sketchup-docs-md/INDEX.md'
FileUtils.mkdir_p('generated-sketchup-docs-md')

File.open(output_path, 'w') do |f|
  f.puts "# SketchUp Ruby API - Documentation Index"
  f.puts ""
  f.puts "This index provides a concise overview of the SketchUp Ruby API for Claude Code."
  f.puts "Use this to quickly find relevant classes, modules, and methods before diving into detailed documentation."
  f.puts ""
  f.puts "**Total documented objects:** #{grouped_objects.values.flatten.size}"
  f.puts ""
  f.puts "---"
  f.puts ""

  # Table of contents
  f.puts "## Namespaces"
  f.puts ""
  sorted_namespaces.each do |ns|
    count = grouped_objects[ns].size
    f.puts "- [#{ns}](##{ns.downcase}) (#{count} objects)"
  end
  f.puts ""
  f.puts "---"
  f.puts ""

  # Detailed listings by namespace
  sorted_namespaces.each do |namespace|
    f.puts "## #{namespace}"
    f.puts ""

    # Sort objects within namespace by path
    objects = grouped_objects[namespace].sort_by { |o| o[:path] }

    objects.each do |obj|
      type_label = obj[:type]
      version_info = obj[:version] ? " _[#{obj[:version]}]_" : ""

      f.puts "- **`#{obj[:path]}`** (#{type_label})#{version_info}"
      f.puts "  - #{obj[:summary]}" unless obj[:summary].empty?
    end

    f.puts ""
  end

  # Footer
  f.puts "---"
  f.puts ""
  f.puts "_Generated by build_index.rb from YARD documentation_"
end

puts "✓ INDEX.md generated at: #{output_path}"
