# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.7'

# Development dependencies
group :development do
  gem 'rubocop'
  gem 'rubocop-performance'
  gem 'sketchup-api-stubs'
  gem 'bundler'
  gem 'rake'
end