AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'sketchup-api-stubs/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 90

Metrics/AbcSize:
  Max: 110

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 35

Metrics/BlockLength:
  Max: 150
