AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'sketchup-api-stubs/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120

# Disable all Metrics cops - noisy and not useful for this codebase
Metrics:
  Enabled: false
